// Liste des noms des sourates du Coran en arabe et français
const suraNames = [
  { number: 1, name: "الفاتحة", nameFr: "Al-Fatiha (L'Ouverture)" },
  { number: 2, name: "البقرة", nameFr: "Al-Baqara (La Vache)" },
  { number: 3, name: "آل عمران", nameFr: "Al-Imran (La Famille d'Imran)" },
  { number: 4, name: "النساء", nameFr: "An-Nisa (Les Femmes)" },
  { number: 5, name: "المائدة", nameFr: "Al-Maida (La Table Servie)" },
  { number: 6, name: "الأنعام", nameFr: "Al-Anam (Les Bestiaux)" },
  { number: 7, name: "الأعراف", nameFr: "Al-Araf (Les Murailles)" },
  { number: 8, name: "الأنفال", nameFr: "Al-Anfal (Le Butin)" },
  { number: 9, name: "التوبة", nameFr: "At-Tawba (Le Repentir)" },
  { number: 10, name: "يونس", nameFr: "Yunus (Jonas)" },
  { number: 11, name: "هود", nameFr: "Hud" },
  { number: 12, name: "يوسف", nameFr: "Yusuf (Joseph)" },
  { number: 13, name: "الرعد", nameFr: "Ar-Rad (Le Tonnerre)" },
  { number: 14, name: "إبراهيم", nameFr: "Ibrahim (Abraham)" },
  { number: 15, name: "الحجر", nameFr: "Al-Hijr" },
  { number: 16, name: "النحل", nameFr: "An-Nahl (Les Abeilles)" },
  { number: 17, name: "الإسراء", nameFr: "Al-Isra (Le Voyage Nocturne)" },
  { number: 18, name: "الكهف", nameFr: "Al-Kahf (La Caverne)" },
  { number: 19, name: "مريم", nameFr: "Maryam (Marie)" },
  { number: 20, name: "طه", nameFr: "Ta-Ha" },
  { number: 21, name: "الأنبياء", nameFr: "Al-Anbiya (Les Prophètes)" },
  { number: 22, name: "الحج", nameFr: "Al-Hajj (Le Pèlerinage)" },
  { number: 23, name: "المؤمنون", nameFr: "Al-Muminun (Les Croyants)" },
  { number: 24, name: "النور", nameFr: "An-Nur (La Lumière)" },
  { number: 25, name: "الفرقان", nameFr: "Al-Furqan (Le Discernement)" },
  { number: 26, name: "الشعراء", nameFr: "Ash-Shuara (Les Poètes)" },
  { number: 27, name: "النمل", nameFr: "An-Naml (Les Fourmis)" },
  { number: 28, name: "القصص", nameFr: "Al-Qasas (Le Récit)" },
  { number: 29, name: "العنكبوت", nameFr: "Al-Ankabut (L'Araignée)" },
  { number: 30, name: "الروم", nameFr: "Ar-Rum (Les Romains)" },
  { number: 31, name: "لقمان", nameFr: "Luqman" },
  { number: 32, name: "السجدة", nameFr: "As-Sajda (La Prosternation)" },
  { number: 33, name: "الأحزاب", nameFr: "Al-Ahzab (Les Coalisés)" },
  { number: 34, name: "سبأ", nameFr: "Saba" },
  { number: 35, name: "فاطر", nameFr: "Fatir (Le Créateur)" },
  { number: 36, name: "يس", nameFr: "Ya-Sin" },
  { number: 37, name: "الصافات", nameFr: "As-Saffat (Les Rangés)" },
  { number: 38, name: "ص", nameFr: "Sad" },
  { number: 39, name: "الزمر", nameFr: "Az-Zumar (Les Groupes)" },
  { number: 40, name: "غافر", nameFr: "Ghafir (Le Pardonneur)" },
  { number: 41, name: "فصلت", nameFr: "Fussilat (Les Versets Détaillés)" },
  { number: 42, name: "الشورى", nameFr: "Ash-Shura (La Consultation)" },
  { number: 43, name: "الزخرف", nameFr: "Az-Zukhruf (L'Ornement)" },
  { number: 44, name: "الدخان", nameFr: "Ad-Dukhan (La Fumée)" },
  { number: 45, name: "الجاثية", nameFr: "Al-Jathiya (L'Agenouillée)" },
  { number: 46, name: "الأحقاف", nameFr: "Al-Ahqaf (Les Dunes)" },
  { number: 47, name: "محمد", nameFr: "Muhammad" },
  { number: 48, name: "الفتح", nameFr: "Al-Fath (La Victoire)" },
  { number: 49, name: "الحجرات", nameFr: "Al-Hujurat (Les Appartements)" },
  { number: 50, name: "ق", nameFr: "Qaf" },
  { number: 51, name: "الذاريات", nameFr: "Adh-Dhariyat (Qui Éparpillent)" },
  { number: 52, name: "الطور", nameFr: "At-Tur (Le Mont)" },
  { number: 53, name: "النجم", nameFr: "An-Najm (L'Étoile)" },
  { number: 54, name: "القمر", nameFr: "Al-Qamar (La Lune)" },
  { number: 55, name: "الرحمن", nameFr: "Ar-Rahman (Le Tout Miséricordieux)" },
  { number: 56, name: "الواقعة", nameFr: "Al-Waqia (L'Événement)" },
  { number: 57, name: "الحديد", nameFr: "Al-Hadid (Le Fer)" },
  { number: 58, name: "المجادلة", nameFr: "Al-Mujadila (La Discussion)" },
  { number: 59, name: "الحشر", nameFr: "Al-Hashr (L'Exode)" },
  { number: 60, name: "الممتحنة", nameFr: "Al-Mumtahina (L'Éprouvée)" },
  { number: 61, name: "الصف", nameFr: "As-Saff (Le Rang)" },
  { number: 62, name: "الجمعة", nameFr: "Al-Jumua (Le Vendredi)" },
  { number: 63, name: "المنافقون", nameFr: "Al-Munafiqun (Les Hypocrites)" },
  { number: 64, name: "التغابن", nameFr: "At-Taghabun (La Grande Perte)" },
  { number: 65, name: "الطلاق", nameFr: "At-Talaq (Le Divorce)" },
  { number: 66, name: "التحريم", nameFr: "At-Tahrim (L'Interdiction)" },
  { number: 67, name: "الملك", nameFr: "Al-Mulk (La Royauté)" },
  { number: 68, name: "القلم", nameFr: "Al-Qalam (La Plume)" },
  { number: 69, name: "الحاقة", nameFr: "Al-Haaqqa (Celle qui montre la Vérité)" },
  { number: 70, name: "المعارج", nameFr: "Al-Maarij (Les Voies d'Ascension)" },
  { number: 71, name: "نوح", nameFr: "Nuh (Noé)" },
  { number: 72, name: "الجن", nameFr: "Al-Jinn (Les Djinns)" },
  { number: 73, name: "المزمل", nameFr: "Al-Muzzammil (L'Enveloppé)" },
  { number: 74, name: "المدثر", nameFr: "Al-Muddathir (Le Revêtu d'un manteau)" },
  { number: 75, name: "القيامة", nameFr: "Al-Qiyama (La Résurrection)" },
  { number: 76, name: "الإنسان", nameFr: "Al-Insan (L'Homme)" },
  { number: 77, name: "المرسلات", nameFr: "Al-Mursalat (Les Envoyés)" },
  { number: 78, name: "النبأ", nameFr: "An-Naba (La Nouvelle)" },
  { number: 79, name: "النازعات", nameFr: "An-Naziat (Les Anges qui arrachent)" },
  { number: 80, name: "عبس", nameFr: "Abasa (Il s'est renfrogné)" },
  { number: 81, name: "التكوير", nameFr: "At-Takwir (L'Obscurcissement)" },
  { number: 82, name: "الانفطار", nameFr: "Al-Infitar (La Rupture)" },
  { number: 83, name: "المطففين", nameFr: "Al-Mutaffifin (Les Fraudeurs)" },
  { number: 84, name: "الانشقاق", nameFr: "Al-Inshiqaq (La Déchirure)" },
  { number: 85, name: "البروج", nameFr: "Al-Buruj (Les Constellations)" },
  { number: 86, name: "الطارق", nameFr: "At-Tariq (L'Astre Nocturne)" },
  { number: 87, name: "الأعلى", nameFr: "Al-Ala (Le Très-Haut)" },
  { number: 88, name: "الغاشية", nameFr: "Al-Ghashiya (L'Enveloppante)" },
  { number: 89, name: "الفجر", nameFr: "Al-Fajr (L'Aube)" },
  { number: 90, name: "البلد", nameFr: "Al-Balad (La Cité)" },
  { number: 91, name: "الشمس", nameFr: "Ash-Shams (Le Soleil)" },
  { number: 92, name: "الليل", nameFr: "Al-Layl (La Nuit)" },
  { number: 93, name: "الضحى", nameFr: "Ad-Duha (Le Jour Montant)" },
  { number: 94, name: "الشرح", nameFr: "Ash-Sharh (L'Ouverture)" },
  { number: 95, name: "التين", nameFr: "At-Tin (Le Figuier)" },
  { number: 96, name: "العلق", nameFr: "Al-Alaq (L'Adhérence)" },
  { number: 97, name: "القدر", nameFr: "Al-Qadr (La Destinée)" },
  { number: 98, name: "البينة", nameFr: "Al-Bayyina (La Preuve)" },
  { number: 99, name: "الزلزلة", nameFr: "Az-Zalzala (La Secousse)" },
  { number: 100, name: "العاديات", nameFr: "Al-Adiyat (Les Coursiers)" },
  { number: 101, name: "القارعة", nameFr: "Al-Qaria (Le Fracas)" },
  { number: 102, name: "التكاثر", nameFr: "At-Takathur (La Course aux Richesses)" },
  { number: 103, name: "العصر", nameFr: "Al-Asr (Le Temps)" },
  { number: 104, name: "الهمزة", nameFr: "Al-Humaza (Le Calomniateur)" },
  { number: 105, name: "الفيل", nameFr: "Al-Fil (L'Éléphant)" },
  { number: 106, name: "قريش", nameFr: "Quraysh (Les Quraysh)" },
  { number: 107, name: "الماعون", nameFr: "Al-Maun (L'Ustensile)" },
  { number: 108, name: "الكوثر", nameFr: "Al-Kawthar (L'Abondance)" },
  { number: 109, name: "الكافرون", nameFr: "Al-Kafirun (Les Infidèles)" },
  { number: 110, name: "النصر", nameFr: "An-Nasr (Les Secours)" },
  { number: 111, name: "المسد", nameFr: "Al-Masad (Les Fibres)" },
  { number: 112, name: "الإخلاص", nameFr: "Al-Ikhlas (Le Monothéisme pur)" },
  { number: 113, name: "الفلق", nameFr: "Al-Falaq (L'Aube naissante)" },
  { number: 114, name: "الناس", nameFr: "An-Nas (Les Hommes)" }
];

export default suraNames;
